name: Build Qemu Source

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Download qemu source
        shell: bash {0}
        run: |
          sudo bash
          curl -o qemu-7.1.0-rc1.tar.xz https://download.qemu.org/qemu-7.1.0-rc1.tar.xz
          tar -xvf qemu-7.1.0-rc1.tar.xz
          cd qemu-7.1.0-rc1

      - name: Build deps
        run: |
           apt install g++ -y
           export PKG="libvirglrenderer-dev  mesa-common-dev libspice-client-gtk-3.0-dev libepoxy-dev libgbm-dev libdrm-dev libsdl2-2.0-0 python3-sdl2 libpng-dev libjpeg-dev libssl-dev libspice-protocol-dev libspice-server-dev libfdt-dev libsdl2-dev libusb-dev libusb-1.0-0-dev build-essential libusbredirhost-dev libseccomp-dev libcap-ng-dev libaio-dev xz-utils wget git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev ninja-build git-email libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev libibverbs-dev libjpeg8-dev libncurses5-dev libnuma-dev librbd-dev librdmacm-dev libsasl2-dev libsdl2-dev libseccomp-dev libsnappy-dev libssh-dev libvde-dev libvdeplug-dev libvte-2.91-dev libxen-dev liblzo2-dev valgrind xfslibs-dev libnfs-dev libiscsi-dev"
           apt install -y $PKG
           pkg-config libjpeg-dev libssl-dev libspice-protocol-dev libspice-server-dev
       
      - name: Build source
        run: |
          mkdir b
          cd b
          mkdir ~/seccond_prefix
          ../configure --prefix=~/seccond_prefix --target-list=i386-softmmu,x86_64-softmmu,arm-softmmu,aarch64-softmmu --enable-guest-agent --enable-vnc --enable-vnc-jpeg --enable-vnc-png --enable-kvm --enable-spice --enable-sdl --enable-virglrenderer --enable-opengl --enable-libusb --enable-usb-redir --enable-gtk --enable-modules --enable-debug --enable-debug-tcg --enable-sanitizers --enable-plugins
          make -j6
          sudo make install

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: qemu_source
          path: ~/seccond_prefix
