name: Build Qemu Source

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - arch: aarch64
            distro: ubuntu20.04
            os: [ubuntu-20.04]

    steps:
      - name: Clone repository
        uses: actions/checkout@v2.1.0

      - name: Download qemu source
        shell: bash
        run: | 
            bash 

      - name: Build deps
        continue-on-error: true
        run: |
           export PKG="libvirglrenderer-dev  mesa-common-dev libspice-client-gtk-3.0-dev"
           export PKG0="libepoxy-dev libgbm-dev libdrm-dev libsdl2-2.0-0 python3-sdl2 libpng-dev libjpeg-dev"
           export PKG1="libssl-dev libspice-protocol-dev libspice-server-dev libfdt-dev libsdl2-dev libusb-dev libusb-1.0-0-dev build-essential libusbredirhost-dev"
           export PKG2="libseccomp-dev libcap-ng-dev libaio-dev xz-utils wget git libglib2.0-dev libfdt-dev libpixman-1-dev zlib1g-dev"
           export PKG3="ninja-build git perl libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev libibverbs-dev libjpeg8-dev libncurses5-dev"
           export PKG4="libnuma-dev librbd-dev librdmacm-dev libsasl2-dev libsdl2-dev libseccomp-dev"
           export PKG5="libsnappy-dev libssh-dev libvde-dev libvdeplug-dev libvte-2.91-dev"
           export PKG6="libxen-dev liblzo2-dev valgrind xfslibs-dev libnfs-dev libiscsi-dev"
           sudo apt update 
           sudo apt install g++ -y
           sudo apt install -y $PKG
           sudo apt install -y $PKG0
           sudo apt install -y $PKG1
           sudo apt install -y $PKG2
           sudo apt install -y $PKG3
           sudo apt install -y $PKG4
           sudo apt install -y $PKG5
           sudo apt install -y $PKG6
           sudo apt install gcc make gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu -y
           sudo apt-get install -y libpixman-1-dev pkg-config-aarch64-linux-gnu
           sudo apt install libglib2.0-dev libgcrypt20-dev zlib1g-dev autoconf automake libtool bison flex libpixman-1-dev libnfs-dev libiscsi-dev libaio-dev libbluetooth-dev libbrlapi-dev libbz2-dev libcap-dev libcap-ng-dev libcurl4-gnutls-dev libgtk-3-dev -y
           pkg-config libjpeg-dev libssl-dev libspice-protocol-dev libspice-server-dev libglib2.0-dev zlib1g-dev libglib2.0
        
       
      - name: Build source
        run: |
          mkdir -p ~/qemu
          cd ~/qemu
          curl -o qemu-7.1.0-rc1.tar.xz https://download.qemu.org/qemu-7.1.0-rc1.tar.xz
          tar -xf qemu-7.1.0-rc1.tar.xz
          cd ~/qemu/qemu-7.1.0-rc1
          mkdir b
          cd b
          mkdir ~/seccond_prefix
          sudo ../configure --cross-prefix=aarch64-linux-gnu- --prefix=~/seccond_prefix --target-list=i386-softmmu,x86_64-softmmu,arm-softmmu,aarch64-softmmu --enable-guest-agent --enable-vnc --enable-vnc-jpeg --enable-kvm --enable-spice --enable-sdl --enable-virglrenderer --enable-opengl --enable-libusb --enable-usb-redir --enable-gtk --enable-modules --enable-debug --enable-debug-tcg --enable-sanitizers --enable-plugins
          make -j6
          sudo make install


      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: qemu_source
          path: ~/seccond_prefix
